// <auto-generated />
using CampsitesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampsitesApi.Migrations
{
    [DbContext(typeof(CampsiteDataContext))]
    [Migration("20220313164901_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("CampsitesApi.Data.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasElectricalHookup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLakeFront")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
